server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/short_rental?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  devtools:
    restart:
#      热部署生效
      enabled: true
#      设置重启目录
      additional-paths: src/main/java

  freemarker:
#    关闭缓存，及时刷新
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl

  thymeleaf:
    prefix: classpath:/temlaates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
mybatis:
#  config-location: classpath:mapping/*.xml
  type-aliases-package: com.example.demo.model
  mapper-locations:  classpath:mapping/*.xml
